name: Colin Narans' Blog
#url: http://cnarans.github.io
description: Web Development in the Cornhusker State

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
