# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Colin's Blog
tagline:          'Web development in the Cornhusker State'
description:      'Web development in the Cornhusker State'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Colin Narans'
  url:            https://twitter.com/Colin_T_N

gems: [redcarpet, jekyll-paginate]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
